<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Mono.Cecil">
      <HintPath>../artifacts/api-docs/tools/mdoc/5.9.3/tools/net6.0/Mono.Cecil.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
